# With services we get a stable IP address for our pods!!!
apiVersion: v1
kind: Service
metadata:
  name: task-service
spec:
  selector: 
    app: task # which pods should be part of that service
  type: LoadBalancer # task is exposed to the outside world
  ports:
    - protocol: "TCP"
      port: 8000
      targetPort: 8000