apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector: 
    app: users # which pods should be part of that service
  type: LoadBalancer
  ports:
      # Expose the users container to the outside world, but not the app container on port 80, which should only be accessible from the users container internally!
    - protocol: "TCP"
      port: 8080
      targetPort: 8080